### ISSUE TITLE
Security Headers Check  D

### ISSUE THREAD

**Issue by miketester19** [beardlyness/NGINE#1]
Hello beardlyness;

First of all thank you so much for creating a such great One Click Install Script. Your hard word and efforts are much appreciated.
Secondly I'm getting D by checking Security Headers.

Please Help.
Thanks

**Comment by beardlyness** [comment]
> Hello beardlyness;
> 
> First of all thank you so much for creating a such great One Click Install Script. Your hard word and efforts are much appreciated.
> Secondly I'm getting D by checking Security Headers.
> 
> Please Help.
> Thanks

Hello Mike,

I'll be making a guide on the SSL Rating for 100% soon. 
Please test your server with https://ssllabs.com and paste the results so I can take a look.

Thanks,
